[project]
name = "pythonproject"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "black>=25.12.0",
    "dotenv>=0.9.9",
    "isort>=7.0.0",
    "langchain-openai>=1.1.6",
    "python-dotenv>=1.2.1",
]
